included:
  - MyNTORewards
  - MyNTORewardsUITests

excluded:
  - Carthage
  - Pods
  - MyNTORewards/UICompnents/CachedAsyncImage.swift

opt_in_rules:
  - empty_count

disabled_rules:
  - trailing_whitespace
  - todo
  - identifier_name
  - multiple_closures_with_trailing_closure
  - type_body_length
  - function_parameter_count
  - cyclomatic_complexity
  - type_name
  - file_length
  - comment_spacing

line_length:
  warning: 160
  error: 220
  ignores_comments: true
